Translated the doc done in french to english + minor french corrections
B2Bitcoin/beBOP pull request #1168
Opened 2024-03-22 13:09 UTC by CypherJack

You might verify that I did stuff correctly enough as I am not really familiar with GitHub.
I think it's okay maybe the commits could have been done in one but I did on the go not knowing how to use git I then used the web app.

2024-03-26 10:49 UTC, Tirodem requested changes
Check comments

2024-03-26 10:49 UTC, Tirodem commented on docs/fr/delivery-management.md
> +### Article Indépendant
"Standalone" (even in french) is a specific e-commerce wording, we keep it as it is.
You can remove this correction.

2024-03-26 10:49 UTC, Tirodem commented on docs/fr/point-of-sale-options.md
> +# Option de point de vente (PoS)
Same as Standalone
You can add ("Point of sale = Point de vente") if you want to explain, but PdV isn't use in french e-commerce, where PoS is a lot.

2024-03-26 10:49 UTC, Tirodem commented on docs/fr/point-of-sale-options.md
> +A noter qu'en cas d'ajout d'article prix libre via alias, le montant du produit sera le montant minimum configuré sur le produit.
Je préfère un "en cas d'ajout d'article à prix libre (PWYW)"

2024-03-27 12:58 UTC, CypherJack commented
Updated

2024-03-27 13:06 UTC, Tirodem approved these changes

2024-03-27 13:07 UTC, merged