Manage a 404 behavior (& other errors) #890
B2Bitcoin/beBOP pull request #1225
Opened 2024-04-22 11:40 UTC by ithiame

2024-04-23 07:44 UTC, Tirodem commented
Testing, pre-review :

- We need a default selected behavior, as the choice is blank on 1st time access
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/7a2b0396-5107-4f96-b224-cbc75f33ecac)
As the default behavior seems to be "Error 404 CMS Page not found" while selecting nothing, check this one if setting value does not exist.

- While choosing "Display error" & updating on /admin/config, I have a crash :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/0141c4e5-ad05-4fa7-9707-a1da6d6caf09)

- While choosing "CMS page / error" without filling the custom error message in page headband :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/2d6123d7-1214-4360-ab6c-a0a178e1777b)
This has to be optional (and **IF** not, error management should be pre-done in UI, raw error while submitting form should not happen)

- Selected behavior doesn't apply, and we still on a display error behavior

- Custom error message in page headband should only be displayed on "Display CMS page error" (here I have it on "redirect to page" and it disappears when clicking on "display cms page error")
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/53de5fda-1532-49ad-9c5c-64371fc5b6c4)

2024-04-23 10:04 UTC, Tirodem commented
✅ Front errors in /admin/config are now OK

❓ Question
- Does it apply only to 404 errors ? (it should)

⚠️ Warning / Thoughts
- I've just thought about /error CMS page not existing yet. In that case, it'll go 404, and if errorBehavior.data = redirectPageError, it'll loop by trying to redirect on itself while not existing. We should exclude 404 processing.

❌ Errors (tested on dev-bootik2)
- redirectPageError does not apply
- displayCMSPageError does not apply
- only "Error 404 CMS Page not found" is displayed

2024-04-23 10:43 UTC, ithiame commented
It apply now on 404 error.

When error page doesn't exist is handled

2024-04-23 11:11 UTC, Tirodem commented
I confirm it applies on 404 error ✅ 

2 things :
🙇 my bad, I did a c&p mistake : headband custom message is meant to be with "Redirect to page" and not "Display CMS page error"
💡 to avoid a 404 loop we should assure that the target URL for "Redirect to page" is an existing CMS page, otherwise, redirect to / with the headband (this field is only meant for internal target URL, not external one)

2024-04-29 11:06 UTC, coyotte508 commented on src/lib/server/renderErrorPage.ts
This file can be removed

2024-04-29 11:06 UTC, coyotte508 commented on src/routes/(app)/[slug]/+page.server.ts
>  	const cmsPage = await collections.cmsPages.findOne(
```suggestion
	let cmsPage = await collections.cmsPages.findOne(
```

2024-04-29 11:06 UTC, coyotte508 commented on src/routes/(app)/[slug]/+page.server.ts
> +		const errorPages = await collections.cmsPages.findOne(
```suggestion
		cmsPage = await collections.cmsPages.findOne(
```

2024-04-29 11:06 UTC, coyotte508 commented on src/routes/(app)/[slug]/+page.server.ts
> +		} else {
```suggestion
		if (!cmsPage) {
```

2024-04-29 11:18 UTC, coyotte508 approved these changes

2024-04-29 11:18 UTC, coyotte508 commented on src/routes/(app)/[slug]/[sub]/[...catchall]/+page.server.ts
> +	const errorPages = await collections.cmsPages.findOne(
```suggestion
	const errorPage = await collections.cmsPages.findOne(
```

2024-04-29 11:19 UTC, coyotte508 requested changes
you need to add +page.svelte for the catchall case

2024-04-29 11:38 UTC, coyotte508 approved these changes

2024-04-29 11:39 UTC, merged