/pos/touch CTA actions : checkout v1 & CTAs actions #1332
B2Bitcoin/beBOP pull request #1337
Opened 2024-06-12 17:08 UTC by ithiame

2024-06-12 19:43 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +			}
Use early return pattern, and use `alert` instead of `console.error`

2024-06-12 19:43 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +	}
Same comment

2024-06-12 22:28 UTC, Tirodem commented
- 🗑 CTA doesn't empty the basket : it does in front, but only the last line is in fact deleted, and if we refresh the page or open the cart elsewhere, the deleted products (minus the last) go back in cart.
- non-dev CTAs : ok ✅ 
- ❎ : ok ✅

2024-07-02 12:16 UTC, coyotte508 commented on src/routes/(app)/cart/+page.server.ts
> +		const cart = await collections.carts.findOne({ user: userIdentifier(locals) });
```suggestion
		const cart = await collections.carts.findOne({ user: userQuery(userIdentifier(locals)) });
```

2024-07-02 13:30 UTC, coyotte508 commented on src/routes/(app)/cart/+page.server.ts
> +		const cart = await collections.carts.findOne({ ...userQuery(userIdentifier(locals)) });
```suggestion
		const cart = await collections.carts.findOne(userQuery(userIdentifier(locals)));
```

2024-07-02 13:30 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +		} else {
The whole point of the early return pattern is there's no need for an `else` afterwards

```suggestion
		}
```

2024-07-02 13:30 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +			if (confirm('Do you want to delete the last cart line ?')) {
Use early return pattern here too

2024-07-02 13:30 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +			if (confirm('Do you want to delete all items from the cart?')) {
Same comments

2024-07-02 16:39 UTC, coyotte508 approved these changes

2024-07-02 16:39 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +			try {
```suggestion
		if (!confirm('Do you want to delete the last cart line ?')) {
			return;
		}
		try {
```

2024-07-02 16:39 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +			try {
```suggestion
		if (!confirm('Do you want to delete all items from the cart?')) {
			return;
		}
		try {
```

2024-07-02 16:54 UTC, coyotte508 requested changes

2024-07-02 16:54 UTC, coyotte508 commented on src/routes/(app)/pos/touch/+page.svelte
> +		>
Please use forms instead.

You can set a different `formaction` on each button - and `use:enhance` on the form to make it dynamic.

You can do the `confirm` call in the `use:enhance` body.

You can also make the buttons disabled when there's no items, that way no need to add the check in the callback

2024-07-03 14:33 UTC, coyotte508 approved these changes

2024-07-11 00:52 UTC, merged